swagger: "2.0"
info:
  version: "1.0.0"
  title: SwaggerNodeJSDemo
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api/v1
schemes:
  # tip: remove http to make production-grade
  - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /topics/{topicId}/questions:
    get:
      description: return questions for given topic
      parameters:
        - name: topicId
          in: path
          description: Id of the topic
          required: true
          type: string
        - name: limit
          in: query
          description: number of questions
          required: true
          type: int
        - name: level
          in: query
          description: difficulty level
          required: true
          type: int
        - name: page
          in: query
          description: page number
          required: true
          type: int
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Questions"

# complex objects have schema definitions
definitions:
  Question:
    required:
      - id
      - title
      - answers
    properties:
      id:
        type: string
      title:
        type: string   
      answers:
        type: array
        items:
          $ref: "#/definitions/Answers"
  Answers:
    required:
        - value
        - isCorrect
    properties:
      value:
        type: string
      isCorrect:
        type: boolean
  Questions:
    type: array
    items:
      $ref: "#/definitions/Question"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string